Imports System.Text.Json
Imports System.IO
Imports System.Linq
Imports System.Security.Policy
Imports System.Windows.Forms.VisualStyles.VisualStyleElement.TrackBar
Imports System.Windows.Forms.VisualStyles.VisualStyleElement.TreeView

Public Class formCreateMob
    Private Sub formFightManager_Load(sender As Object, e As EventArgs) Handles MyBase.Load

    End Sub

    Private Sub btnSavePerso_Click(sender As Object, e As EventArgs) Handles btnSavePerso.Click
        Dim strRetour As String = "{""IdRace"": """ & txtIdChose.Text & """,""NomRace"": """ & txtNomChose.Text & """,""Vitesse"": 6,""TailleMini"": 0,""TailelMaxi"": 0,""PoidsMini"": 0,""PoidsMaxi"": 0,""Taille"": ""P"",""Vision"": ""Dans le noir"",""Caracteristiques"": [{""Nom"": ""Force"",""Valeur"": " & txtForce.Text & "},{""Nom"":""Constitution"",""Valeur"": " & txtConstitution.Text & "},{""Nom"": ""Dexterite"",""Valeur"": " & txtDexterite.Text & "},{""Nom"": ""Intelligence"",""Valeur"": " & txtIntelligence.Text & "},{""Nom"": ""Sagesse"",""Valeur"": " & txtSagesse.Text & "},{""Nom"": ""Charisme"",""Valeur"": " & txtCharisme.Text & "}],""Competences"": [{""Nom"": ""Acrobaties"",""Valeur"": " & txtAcrobaties.Text & "},{""Nom"": ""Arcanes"",""Valeur"": " & txtArcanes.Text & "},{""Nom"": ""Athletisme"",""Valeur"": " & txtAthletisme.Text & "},{""Nom"": ""Bluff"",""Valeur"": " & txtBluff.Text & "},{""Nom"": ""ConnDeLaRue"",""Valeur"": " & txtConnlaRue.Text & "},{""Nom"": ""Diplomatie"",""Valeur"": " & txtDiplomatie.Text & "},{""Nom"": ""Discretion"",""Valeur"": 1" & txtDiscretion.Text & "},{""Nom"": ""Endurance"",""Valeur"": " & txtEndurance.Text & "},{""Nom"": ""Exploration"",""Valeur"": " & txtExploration.Text & "},{""Nom"": ""Histoire"",""Valeur"": " & txtHistoire.Text & "},{""Nom"": ""Intuition"",""Valeur"": " & txtIntuition.Text & "},{""Nom"": ""Intimidation"",""Valeur"": " & txtIntimidation.Text & "},{""Nom"": ""Larcin"",""Valeur"": 1" & txtLarcin.Text & "},{""Nom"": ""Nature"",""Valeur"": " & txtNature.Text & "},{""Nom"": ""Perception"",""Valeur"": " & txtPerception.Text & "},{""Nom"": ""Religion"",""Valeur"": " & txtReligion.Text & "},{""Nom"": ""Soins"",""Valeur"": " & txtSoins.Text & "}],""Sauvegardes"": [{""Nom"": ""ClasseArmure"",""Valeur"": " & txtCA.Text & "},{""Nom"": ""Vigueur"",""Valeur"": " & txtVigueur.Text & "},{""Nom"": ""Reflexe"",""Valeur"": " & txtReflexes.Text & "},{""Nom"": ""Volonte"",""Valeur"": " & txtVolonte.Text & "}]},"
        strRetour = strRetour & "{""IdClasse"":  """ & txtIdChose.Text & """,""NomClasse"": """ & txtNomChose.Text & """,""PointVieBase"": " & txtPointVieBase.Text & ",""PointVieNiveau"": " & txtPointVieBase.Text & ",""Recuperation"": 0,""Sauvegardes"": [{""Nom"": ""ClasseArmure"",""Valeur"": 0},{""Nom"": ""Vigueur"",""Valeur"": 0},{""Nom"": ""Reflexe"",""Valeur"": 0},{""Nom"": ""Volonte"",""Valeur"": 0}],""NombreCompetence"": 0,""Competences"": []},"

        My.Computer.Clipboard.SetText(strRetour)
    End Sub

    Private Sub btnPersoVrac_Click(sender As Object, e As EventArgs) Handles btnPersoVrac.Click
        Dim strRetour As String = ""
        Dim matrix = New String(,) {{"Frondeur_kobold", "Frondeur kobold", "6", "6", "9", "12", "17", "9", "12", "10", "13", "12", "14", "12", "8", "0", "0", "0", "0", "0", "10", "0", "0", "0", "0", "0", "10", "0", "1", "0", "0"}, {"Sbire_kobold", "Sbire kobold", "0", "0", "8", "12", "16", "9", "12", "10", "15", "11", "13", "11", "0", "0", "0", "0", "0", "0", "5", "0", "0", "0", "0", "0", "5", "0", "1", "0", "0"}, {"Dracoecu_kobold", "Draco-écu kobold", "8", "8", "14", "12", "13", "9", "12", "10", "18", "14", "13", "13", "7", "0", "0", "0", "0", "0", "9", "0", "0", "0", "0", "0", "9", "0", "2", "0", "0"}, {"Franctireur_kobold", "Franc-tireur kobold", "8", "8", "8", "11", "16", "6", "10", "15", "15", "11", "14", "13", "8", "0", "0", "0", "0", "0", "10", "0", "0", "0", "0", "0", "10", "0", "0", "0", "0"}, {"Dracopretre_kobold", "Dracoprêtre kobold", "6", "6", "9", "12", "16", "9", "17", "12", "17", "13", "15", "15", "0", "0", "0", "0", "0", "0", "11", "0", "0", "0", "0", "0", "11", "0", "0", "0", "0"}}
        For index = 0 To matrix.GetUpperBound(0)
            strRetour = strRetour & $"{{""IdRace"": ""{matrix(index, 0)}"",""NomRace"": ""{matrix(index, 1)}"",""Vitesse"": 6,""TailleMini"": 0,""TailelMaxi"": 0,""PoidsMini"": 0,""PoidsMaxi"": 0,""Taille"": ""P"",""Vision"": ""Dans le noir"",""Caracteristiques"": [{{""Nom"": ""Force"",""Valeur"": {matrix(index, 4)}}},{{""Nom"":""Constitution"",""Valeur"": {matrix(index, 5)}}},{{""Nom"": ""Dexterite"",""Valeur"": {matrix(index, 6)}}},{{""Nom"": ""Intelligence"",""Valeur"": {matrix(index, 7)}}},{{""Nom"": ""Sagesse"",""Valeur"": {matrix(index, 8)}}},{{""Nom"": ""Charisme"",""Valeur"": {matrix(index, 9)}}}],""Competences"": [{{""Nom"": ""Acrobaties"",""Valeur"": {matrix(index, 14)}}},{{""Nom"": ""Arcanes"",""Valeur"": {matrix(index, 15)}}},{{""Nom"": ""Athletisme"",""Valeur"": {matrix(index, 16)}}},{{""Nom"": ""Bluff"",""Valeur"": {matrix(index, 17)}}},{{""Nom"": ""ConnDeLaRue"",""Valeur"": {matrix(index, 18)}}},{{""Nom"": ""Diplomatie"",""Valeur"": {matrix(index, 19)}}},{{""Nom"": ""Discretion"",""Valeur"": 1{matrix(index, 20)}}},{{""Nom"": ""Endurance"",""Valeur"": {matrix(index, 21)}}},{{""Nom"": ""Exploration"",""Valeur"": {matrix(index, 22)}}},{{""Nom"": ""Histoire"",""Valeur"": {matrix(index, 23)}}},{{""Nom"": ""Intuition"",""Valeur"": {matrix(index, 24)}}},{{""Nom"": ""Intimidation"",""Valeur"": {matrix(index, 25)}}},{{""Nom"": ""Larcin"",""Valeur"": 1{matrix(index, 26)}}},{{""Nom"": ""Nature"",""Valeur"": {matrix(index, 27)}}},{{""Nom"": ""Perception"",""Valeur"": {matrix(index, 28)}}},{{""Nom"": ""Religion"",""Valeur"": {matrix(index, 29)}}},{{""Nom"": ""Soins"",""Valeur"": {matrix(index, 30)}}}],""Sauvegardes"": [{{""Nom"": ""ClasseArmure"",""Valeur"": {matrix(index, 10)}}},{{""Nom"": ""Vigueur"",""Valeur"": {matrix(index, 11)}}},{{""Nom"": ""Reflexe"",""Valeur"": {matrix(index, 12)}}},{{""Nom"": ""Volonte"",""Valeur"": {matrix(index, 13)}}}]}},"
            strRetour = strRetour & $"{{""IdClasse"":  ""{matrix(index, 0)}"",""NomClasse"": ""{matrix(index, 1)}"",""PointVieBase"": {matrix(index, 2)},""PointVieNiveau"": {matrix(index, 2)},""Recuperation"": 0,""Sauvegardes"": [{{""Nom"": ""ClasseArmure"",""Valeur"": 0}},{{""Nom"": ""Vigueur"",""Valeur"": 0}},{{""Nom"": ""Reflexe"",""Valeur"": 0}},{{""Nom"": ""Volonte"",""Valeur"": 0}}],""NombreCompetence"": 0,""Competences"": []}},"
        Next
        My.Computer.Clipboard.SetText(strRetour)
    End Sub
End Class